truncate league_config;
INSERT INTO `league_config` (`Id`,`season`,`round`,`created_time`,`updated_time`) VALUES (1,1,1,'2010-03-19 21:17:58','2010-03-19 21:18:09');

update league_matchs set status = 0;
update league_teams set win = 0, lose=0, net_points=0 ,status=0, team_id=-1;
truncate user_info;
truncate team;
truncate team_arena;
truncate team_ad;
truncate matchs;
truncate team_tactical;
truncate team_tactical_detail;
truncate youth_player;
truncate profession_player;
truncate all_finance;
truncate season_finance;
truncate match_stat;
truncate unions;
truncate union_member;
truncate out_message;
truncate message;
truncate training_center;
truncate training_remain;
truncate team_ticket_history;
truncate match_nodosity_detail;
truncate match_nodosity_main;
truncate match_nodosity_tactical_detail;
truncate match_not_in_player;
truncate pro_player_career_stat_total;
truncate pro_player_season_stat_total;
truncate friends;