
CREATE TABLE `free_player` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `no` varchar(32) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `name_base` varchar(255) DEFAULT NULL,
  `player_no` int(5) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `position` varchar(2) DEFAULT NULL,
  `position_base` varchar(2) DEFAULT NULL,
  `stature` int(11) DEFAULT NULL,
  `avoirdupois` int(11) DEFAULT NULL,
  `team_Id` bigint(20) DEFAULT NULL,
  `ability` double DEFAULT NULL,
  `shooting` smallint(6) DEFAULT NULL,
  `speed` smallint(6) DEFAULT NULL,
  `strength` smallint(6) DEFAULT NULL,
  `bounce` smallint(6) DEFAULT NULL,
  `stamina` smallint(6) DEFAULT NULL,
  `trisection` smallint(6) DEFAULT NULL,
  `dribble` smallint(6) DEFAULT NULL,
  `pass` smallint(6) DEFAULT NULL,
  `backboard` smallint(6) DEFAULT NULL,
  `steal` smallint(6) DEFAULT NULL,
  `blocked` smallint(6) DEFAULT NULL,
  `shooting_max` smallint(6) DEFAULT NULL,
  `speed_max` smallint(6) DEFAULT NULL,
  `strength_max` smallint(6) DEFAULT NULL,
  `bounce_max` smallint(6) DEFAULT NULL,
  `stamina_max` smallint(6) DEFAULT NULL,
  `trisection_max` smallint(6) DEFAULT NULL,
  `dribble_max` smallint(6) DEFAULT NULL,
  `pass_max` smallint(6) DEFAULT NULL,
  `backboard_max` smallint(6) DEFAULT NULL,
  `steal_max` smallint(6) DEFAULT NULL,
  `blocked_max` smallint(6) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `betch_no` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `no` (`no`),
  KEY `betch_no` (`betch_no`),
  KEY `position` (`position`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `player_betch_log` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `betch_no` varchar(100) DEFAULT NULL,
  `is_success` tinyint(1) DEFAULT NULL,
  `info` text,
  `created_time` datetime DEFAULT NULL,
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `betch_no` (`betch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;