// WangDunProxy.idl : IDL source for WangDunProxy
//

// This file will be processed by the MIDL tool to
// produce the type library (WangDunProxy.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(FD16CD5D-6D89-4AF1-81D9-5F556BE47683),
	dual,
	nonextensible,
	helpstring("IWandDunClient Interface"),
	pointer_default(unique)
]
interface IWandDunClient : IDispatch{
};
[
	uuid(B65DE695-B606-4781-B207-F85498A5329C),
	version(1.0),
	helpstring("WangDunProxy 1.0 Type Library")
]
library WangDunProxyLib
{
	importlib("stdole2.tlb");
	[
		uuid(7131E933-5B8B-4ED0-BD55-A055D246162A),
		helpstring("WandDunClient Class")
	]
	coclass WandDunClient
	{
		[default] interface IWandDunClient;
	};
};
