INSERT INTO `action_desc` VALUES ('29', 'success', ' ~1~接到~3~的传球，直接隔着两名防守队员来了个大力扣篮', 'CatchSlamDunk', 'not_foul', '7', null);
INSERT INTO `action_desc` VALUES ('30', 'success', ' ~1~与~3~做了个挡拆配合,过了防守队员~2~,篮下已经无防球员，~1~轻松将球扣进', 'CatchSlamDunk', 'not_foul', '4', null);
INSERT INTO `action_desc` VALUES ('31', 'success', '~1~背靠防守球员~2~,突然一个转身切入篮下，反身将球扣进,精彩', 'CatchSlamDunk', 'not_foul', '5', null);
INSERT INTO `action_desc` VALUES ('32', 'failure', '~1~的扣篮被~2~拍了一下,没进!', 'CatchSlamDunk', 'blocked', '2', null);
INSERT INTO `action_desc` VALUES ('33', 'failure', '~1~接到~3~的妙传,空中想直接扣篮,~2~跳起防守,一个大帽,直接把球扇了出去,~2~的防守能力太强了', 'CatchSlamDunk', 'blocked', '2', null);
INSERT INTO `action_desc` VALUES ('34', 'failure', '~3~看到~1~了的跑位,假装突破,突然把球往空中一抛,想和~1~来一个空中接力，~2~占位准确,一个大帽，直接把球扇了出去!', 'CatchSlamDunk', 'blocked', '2', null);
INSERT INTO `action_desc` VALUES ('35', 'failure', '~3~运球突破,吸引了对方两名防守队员的包夹,~1~这边已经空了,~3~心领神会,在两名防守球员中间把球一扔,~1~接球想来一个暴扣,但还是被~2~硬生生的盖了下来!', 'CatchSlamDunk', 'blocked', '2', null);
INSERT INTO `action_desc` VALUES ('36', 'failure', '~1~和~3~玩了个二过一后想直接扣篮,~2~从背后直接把球打掉!', 'CatchSlamDunk', 'blocked', '2', null);
INSERT INTO `action_desc` VALUES ('37', 'success', '~1~侧身运球过了一名防守球员,抢在补防球员之前将球投入篮筐', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('38', 'success', '~1~真是个投篮机器,接球不做任何调整,直接出手,皮球空心入网', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('39', 'success', '~1~抢在防守球员的封盖之前出手命中', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('40', 'success', '~1~脚踩三分线,高高跃起投篮,命中\"', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('41', 'success', '~1~跳投命中', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('42', 'success', '~1~用身体强吃对手,在对手头顶打板命中', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('43', 'success', '~1~接~3~隐蔽的背后传球,突破上篮得手', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('44', 'success', '~1~背身单打,用身体挤开防守球员,一个右手勾手投篮,命中', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('45', 'success', '~1~底线切入,过了防守队员~2~,轻松的打篮入筐!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('46', 'success', '~1~和~3~做了一个挡拆配合后,以一记精准的半截篮结束了本次进攻!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('47', 'success', '~1~中圈附近得球后,晃过~2~,一个很不标准的投篮,命中!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('48', 'success', '~1~倚住防守队员,强行出手! 球居然进了', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('49', 'success', '~1~假装突破,骗过防守队员,突然出手投篮,球进', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('50', 'success', '~1~接球直接出手,一气呵成,漂亮的弧线!球空心入网', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('51', 'success', '~1~等候在底线 ,出了空档,接到队友隐蔽的传球,出手,球进!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('52', 'success', '~1~等候在底线 ,出了空档,接到队友隐蔽的传球,出手,球进! ', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('53', 'failure', '~1~今天的状态不是很好,连这种空位投篮也不进', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('54', 'failure', '~1~在对手严密的防守之前强行出手,不中', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('55', 'failure', '~1~脚踩三分线,高高跃起投篮,投了个三不沾', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('56', 'failure', '~1~跳投,不中', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('57', 'failure', '~1~想用身体强吃对手,球没进', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('58', 'failure', '~1~接~2~隐蔽的背后传球,突破上篮,不进', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('59', 'failure', '~1~背身单打,用身体挤开防守球员,一个右手勾手投篮,球弹筐而出', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('60', 'failure', '~1~底线切入,过了防守队员~2~,但投篮还是被干扰了一下,没进!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('61', 'failure', '~1~和~3~做了一个挡拆配合后,投篮不进!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('62', 'failure', '~1~跑动中接球,在二分线附近得到队友传球,一个挑篮 ,力量有些大,球砸在篮板上', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('63', 'failure', '~1~跑动中接球,在二分线附近得到队友传球,一个挑篮 ,力量小了一点,球砸在篮框上', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('64', 'failure', '~1~倚住防守队员,强行出手! 投了个三不沾', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('65', 'failure', '~1~假装突破, 骗过防守队员,突然出手投篮,球被防守队员干扰了一下,没进', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('66', 'failure', '~1~接球直接出手,一气呵成,漂亮的弧线!但球还是差一点没进', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('67', 'failure', '~1~等候在底线 ,出了空档,接到队友隐蔽的传球,出手,球偏筐而出!', 'ShortShoot', 'not_foul', '2', null);
INSERT INTO `action_desc` VALUES ('68', 'failure', '~1~侧身运球过了一名防守球员,但投篮被补防的球员干扰了一下,没进', 'ShortShoot', 'not_foul', '2', null);
