namespace Web.Helper
{
    using System;

    public class PlayerData
    {
        public bool blChangeName;
        public bool blIsDevision;
        public bool blIsRetire;
        public bool blIsStaff;
        public bool blSellAss;
        public bool blShowSkill;
        private DateTime dtEndBidTime;
        public int intAbility;
        public int intAge;
        public int intAttack;
        public int intAttackMax;
        public int intBidCount;
        public int intBidderID;
        public int intBidPrice;
        public int intBidStatus;
        public int intBirthTurn;
        public int intBlock;
        public int intBlockMax;
        public int intBodyPotential;
        public int intCategory;
        public int intContract;
        public int intDefense;
        public int intDefenseMax;
        public int intDribble;
        public int intDribbleMax;
        public int intHappy;
        public int intHardness;
        public int intHeight;
        public int intHeightPoint;
        public int intIsHonor;
        public int intJump;
        public int intJumpMax;
        public int intLastAssist;
        public int intLastBlock;
        public int intLastPlayed;
        public int intLastRebound;
        public int intLastScore;
        public int intLastSteal;
        public int intLeadship;
        public int intLifeAssist;
        public int intLifeBlock;
        public int intLifeRebound;
        public int intLifeScore;
        public int intLifeSteal;
        public int intMarketLvl;
        public int intMVPValue;
        public int intNumber;
        public int intPass;
        public int intPassMax;
        public int intPlayed;
        public int intPlayedYear;
        public int intPoint3;
        public int intPoint3Max;
        public int intPop;
        public int intPos;
        public int intPower;
        public int intPV;
        public int intRebound;
        public int intReboundMax;
        public int intRetireAge;
        public int intSalary;
        public int intSeasonAssist;
        public int intSeasonBlock;
        public int intSeasonPlayed;
        public int intSeasonRebound;
        public int intSeasonScore;
        public int intSeasonShirt;
        public int intSeasonSteal;
        public int intShirt;
        public int intShot;
        public int intShotMax;
        public int intSkillPotential;
        public int intSpeed;
        public int intSpeedMax;
        public int intStamina;
        public int intStaminaMax;
        public int intStatus;
        public int intSteal;
        public int intStealMax;
        public int intStrength;
        public int intStrengthMax;
        public int intSuspend;
        public int intTeam;
        public int intTeamDay;
        public int intTeamMax;
        public int intTrainAType;
        public int intTrainPoint;
        public int intTrainType;
        public int intUserID;
        public int intWeight;
        public int intWeightPoint;
        public long longPlayerID;
        public string strEvent;
        public string strFace;
        public string strMarketCode;
        public string strName;
        public string strOldName;
        public string strPassword;
        public string strPKName;
        public string strUserName;

        public PlayerData(long longPlayerID)
        {
        }

        public PlayerData(string strUserName, string strPassword)
        {
        }

        public PlayerData(string strUserName, string strPassword, string strPKName, string strName, string strFace, string strEvent, string strMarketCode, string strOldName, int intUserID, int intCategory, int intStatus, int intAge, int intPos, int intNumber, int intSalary, int intContract, int intPower, int intHappy, int intHeight, int intWeight, int intHeightPoint, int intWeightPoint, int intTrainPoint, int intTrainType, int intBodyPotential, int intSkillPotential, int intSpeed, int intJump, int intStrength, int intStamina, int intShot, int intPoint3, int intDribble, int intPass, int intRebound, int intSteal, int intBlock, int intAttack, int intDefense, int intTeam, int intSpeedMax, int intJumpMax, int intStrengthMax, int intStaminaMax, int intShotMax, int intPoint3Max, int intDribbleMax, int intPassMax, int intReboundMax, int intStealMax, int intBlockMax, int intAttackMax, int intDefenseMax, int intTeamMax, int intAbility, int intPV, int intBidPrice, DateTime dtEndBidTime, int intLastPlayed, int intPlayed, int intLifeScore, int intLifeRebound, int intLifeAssist, int intLifeBlock, int intLifeSteal, int intSeasonPlayed, int intSeasonScore, int intSeasonRebound, int intSeasonAssist, int intSeasonBlock, int intSeasonSteal, int intLastScore, int intLastRebound, int intLastAssist, int intLastBlock, int intLastSteal, int intSuspend, int intBidCount, int intPlayedYear, int intTeamDay, int intIsHonor, int intTrainAType, int intRetireAge, int intPop, int intShirt, int intSeasonShirt, int intBidStatus, int intBidderID, int intMVPValue, int intBirthTurn, int intMarketLvl, int intHardness, int intLeadship, bool blIsRetire, bool blIsDevision, bool blIsStaff, bool blShowSkill, bool blChangeName, bool blSellAss)
        {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strPKName = strPKName;
            this.strName = strName;
            this.strFace = strFace;
            this.strEvent = strEvent;
            this.strMarketCode = strMarketCode;
            this.strOldName = strOldName;
            this.intUserID = intUserID;
            this.intCategory = intCategory;
            this.intStatus = intStatus;
            this.intAge = intAge;
            this.intPos = intPos;
            this.intNumber = intNumber;
            this.intSalary = intSalary;
            this.intContract = intContract;
            this.intPass = intPower;
            this.intHappy = intHappy;
            this.intHeight = intHeight;
            this.intWeight = intWeight;
            this.intHeightPoint = intHeightPoint;
            this.intWeightPoint = intWeightPoint;
            this.intTrainPoint = intTrainPoint;
            this.intTrainType = intTrainType;
            this.intBodyPotential = intBodyPotential;
            this.intSkillPotential = intSkillPotential;
            this.intSpeed = intSpeed;
            this.intJump = intJump;
            this.intStrengthMax = intStrengthMax;
            this.intStamina = intStamina;
            this.intShot = intShot;
            this.intPoint3 = intPoint3;
            this.intDribble = intDribble;
            this.intPass = intPass;
            this.intRebound = intRebound;
            this.intSteal = intSteal;
            this.intBlock = intBlock;
            this.intAttack = intAttack;
            this.intDefense = intDefense;
            this.intTeam = intTeam;
            this.intSpeed = intSpeedMax;
            this.intJumpMax = intJumpMax;
            this.intStrengthMax = intStrengthMax;
            this.intLastPlayed = intLastPlayed;
            this.intShotMax = intShotMax;
            this.intPoint3Max = intPoint3Max;
            this.intDribbleMax = intDribbleMax;
            this.intPassMax = intPassMax;
            this.intReboundMax = intReboundMax;
            this.intStealMax = intStealMax;
            this.intBlockMax = intBlockMax;
            this.intAttackMax = intAttackMax;
            this.intDefenseMax = intDefenseMax;
            this.intTeamMax = intTeamMax;
            this.intAbility = intAbility;
            this.intPV = intPV;
            this.intBidPrice = intBidPrice;
            this.dtEndBidTime = dtEndBidTime;
            this.intSeasonSteal = intSeasonSteal;
            this.intLastScore = intSeasonShirt;
            this.intLastRebound = intLastRebound;
            this.intLastAssist = intLastAssist;
            this.intBlock = intLastBlock;
            this.intLastSteal = intLifeSteal;
            this.intSuspend = intSuspend;
            this.intBidCount = intBidCount;
            this.intPlayedYear = intPlayedYear;
            this.intTeamDay = intTeamDay;
            this.intIsHonor = intIsHonor;
            this.intTrainAType = intTrainAType;
            this.intRetireAge = intRetireAge;
            this.intPop = intPop;
            this.intShirt = intShirt;
            this.intSeasonShirt = intSeasonShirt;
            this.intBidStatus = intBidStatus;
            this.intBidderID = intBidderID;
            this.intMVPValue = intMVPValue;
            this.intBirthTurn = intBirthTurn;
            this.intMarketLvl = intMarketLvl;
            this.intHardness = intHardness;
            this.intLeadship = intLeadship;
            this.blIsRetire = blIsRetire;
            this.blIsDevision = blIsDevision;
            this.blIsStaff = blIsStaff;
            this.blShowSkill = blShowSkill;
            this.blChangeName = blChangeName;
            this.blSellAss = blSellAss;
        }
    }
}

